version: "3.9"

services:
  db:
    image: postgres:16
    container_name: minha-api-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipass
      POSTGRES_DB: minha_api
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
